### ISSUE TITLE
Problem with download_captcha function

### ISSUE THREAD

**Issue by MislavSag** [decryptr/decryptr#10]
The download_captcha function doesn't download caprcha from the site. If I run following code:

```
url <- "http://pdv-reg.porezna-uprava.hr/RpoProvjeriObveznikaPdvWeb/upit"
files <- download_captcha(url, n = 5, path = "./img")
```
it doesn't download captcha picture, but all HTML code of the site.
This is how the files names look like:
captcha209c7fe60cb.html; charset=UTF-8
captcha209c12a77ae1.html; charset=UTF-8
captcha209c780443ab.html; charset=UTF-8
....

**Comment by dfalbel** [comment]
You will need to find the direct link for the captcha omg. In this site it's http://pdv-reg.porezna-uprava.hr/RpoProvjeriObveznikaPdvWeb/stickyImg

**Comment by MislavSag** [comment]
Fast and simple answer. Thanks!

**Comment by ctlente** [comment]
I'm very sorry about that @MislavSag! It was my fault, I mistyped the name of a variable in the source code...

Could you please reinstall the package and try again?

**Comment by dfalbel** [comment]
Maybe.. I would go for 5000.

**Comment by MislavSag** [comment]
Ok. thanks

**Comment by israelBalbuena** [comment]
Hi, I have a doubt: in the next page what would be the direct url to the captcha ? : https://agsc.siat.sat.gob.mx/PTSC/ValidaRFC/index.jsf 

I am trying to download the captcha with the package decryptr, but I have not been successful. My code is:

` url <- "https://agsc.siat.sat.gob.mx/PTSC/ValidaRFC/index.jsf/"

download_captcha(url, n=1,path =  "./img") `

I would really appreciate your help.

**Comment by clente** [comment]
You might have to download these CAPTCHAs manually. It seems like you need a POST request to the following URL: https://agsc.siat.sat.gob.mx/PTSC/ValidaRFC/captchaReload
