### ISSUE TITLE
Error: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by MislavSag** [decryptr/decryptr#11]
Hi again,

I ran following code:
```
# URL of a captcha (for illustrative purposes I'll be using
# TRT's URL, but you can use whichever URL you want)
url <- "http://pdv-reg.porezna-uprava.hr/RpoProvjeriObveznikaPdvWeb/stickyImg"

# Download captcha from URL
files <- download_captcha(url, n = 1000, path = "./img")

# Classify captchas (if answers weren't supplied,
# I'd be promped for interactive classification)
new_files <- classify(files, answers = NULL, path = ./img", rm_old = TRUE)

# Read answered captchas
captchas <- read_captcha(new_files, ans_in_path = TRUE)

# Use captchas to train a model
model <- train_model(captchas, verbose = FALSE, path = "./model.hdf5")
```
and got an error:
```
Error in m[, what] <- y : 
  number of items to replace is not a multiple of replacement length
```
Not sure what's happening here.

**Comment by ctlente** [comment]
@MislavSag I wasn't able to reproduce this error. Could you please show me your `sessionInfo()`?

Also, this error might happen when the answers to the captchas have different lengths; please make sure you haven't mistyped anything during `classify()`! In your specific case every answer should have 5 characters, therefore the code bellow should return `TRUE`:

```r
"./img" %>%
    list.files(pattern = "\\.png") %>%
    stringr::str_extract("(?<=_).+(?=\\.png)") %>%
    stringr::str_length() %>%
    all(. == 5)
```

**Comment by MislavSag** [comment]
It works now. It would be good to add condition as an assertion.

Accuracy is low but hope will be better with more examples and epochs.

Thanks

**Comment by ctlente** [comment]
Added a check in 558df422274572d7a7629e654aab71c0ac356b3e
