### ISSUE TITLE
get_answers with vocabulary argument

### ISSUE THREAD

**Issue by dfalbel** [decryptr/decryptr#13]
@ctlente Qual sua opinião sobre adicionar um parâmetro de vocabulário nessa função e consequentemente no read_captcha?

A matriz que ele retorna de resposta p/ um captcha não faz muito sentido pq as colunas não representam sempre os mesmos elementos do vocabulário. Além de que dependendo da quantidade de captchas que vc carrega o `join_captchas` pode retornar arrays de tamanhos diferentes.

Se vc estiver de acordo eu implemento aqui!

**Comment by ctlente** [comment]
Eu acho uma boa! Vc vai implementar então?
