### ISSUE TITLE
Should we allow users to choose if they want grey scale captchas?

### ISSUE THREAD

**Issue by dfalbel** [decryptr/decryptr#15]
Atualmente estamos transformando os captchas p/ preto e branco automaticamente, mas acho que para alguns captchas a informação da cor pode ser relevante...

Será que podemos adicionar um argumento p/ possibilitar isso?

**Comment by ctlente** [comment]
Sim, eu pensei em trocar isso quando conseguíssemos impelementar o captcha de duas cores... Mas dado que não estamos conseguindo, talvez seja melhor já deixar essa opção :/

**Comment by jtrecenti** [comment]
Acho que o roadmap é

1. fazer o modelo colorido funcionar no TJMG, que é o mais fácil
2. fazer o modelo colorido funcionar em todos os casos
3. deixar sempre o modelo colorido, pq teoricamente nunca atrapalha tratar com os 3 channels iniciais.

**Comment by ctlente** [comment]
@jtrecenti Quando vc diz "fazer funcionar" vc quer dizer retreinar os modelos pra que eles aceitem captchas coloridos? Acho que isso não é necessário, não é melhor só colocar esse argumento `bw` que converte a imagem pra preto e branco quando o modelo requer?

Inclusive @dfalbel, talvez fosse melhor esse preto e branco não ser um argumento, mas sim uma flag no objeto `modelo` que indica se deve acontecer essa conversão.

**Comment by jtrecenti** [comment]
sim, quero dizer retreinar. O meu ponto é que, se quisermos que nossos modelos funcionem com captchas, um bom exemplo pra treinar é o TJMG. No limite, nenhum captcha precisa ser considerado como preto e branco, e podemos usar colorido sempre.

**Comment by djalmaaraujo** [comment]
To chegando do nada, mas tem sites por ex (de sao paulo), que o captcha tem 2 problemas:

1 - Você precisa digitar apenas certos caracteres
2 - Estes "certos" são uma cor que é escrita na pagina.

Entao basicamente é: Digite apenas os caracteres ROSAS. E essa cor é dinâmica. Eu estou usanto uma API para retornar todos os caracteres, mas esbarrei na parte de detectar a cor correta.

Só a cargo de informação.

**Comment by dfalbel** [comment]
Valeu @djalmaaraujo ! Tenho uma base de algum captcha que é dessa forma. Ainda vamos incluir esta forma no decryptr!

**Comment by djalmaaraujo** [comment]
@dfalbel Eu estou fazendo um sistema que utilize api de terceiros, e descobri essa lib de vocês hoje. Muito irado. O único problema é que eu preciso ficar tentando no sistema. No caso, vocês resolvem e retornam possibilidades, dai eu preciro criar um crawler que fique tentando, ne isso?

Se você tiver a base que você falou, adoraria ver o source code.

**Comment by clente** [comment]
Fechando por inatividade. Reabrir caso necessário.
