### ISSUE TITLE
Parâmetro para decifrar Captcha do Sefaz

### ISSUE THREAD

**Issue by dorcilio** [decryptr/decryptr#17]
Olá,
Faço uso da biblioteca de vocês e é excelente.
Estou trabalhando com serviços do Sefaz MT, teria algum parâmetro para decifrar desse tipo de Captcha?
[Exemplos de Imagem](https://imgur.com/a/iGmKS6o)

Obrigado desde já!
Atenciosamente,
Dorcílio Neto.

**Comment by dfalbel** [comment]
Olá Dorcílio,

Ainda não temos... Podemos ajudá-lo se conseguir produzir um banco de dados de imagens (~20K com o conteúdo do captcha tageado)

Abraços,

**Comment by clente** [comment]
Fechando por inatividade. Reabrir caso necessário.
