### ISSUE TITLE
How use predict for rfb

### ISSUE THREAD

**Issue by fabioravila** [decryptr/decryptr#2]
How use the code below wit rfb model?
`# Load model (install decryptrModels package first)
keras_tjmg <- decryptrModels::read_model('tjmg')
data('tjmg', package = 'decryptr')
tjmg$model <- keras_tjmg

captcha %>% 
  read_captcha() %>% 
  predict(tjmg, arq = .)`

**Comment by jtrecenti** [comment]
Sorry, the API is not mature yet. Currently this is the code you should use.

```
keras_rfb <- decryptrModels::read_model('rfb')

library(decryptr)
captcha <- download_rfb('.')
plot(read_captcha(captcha))

captcha %>%
  read_captcha() %>%
  predict(keras_rfb, arq = .)
```

**Comment by fabioravila** [comment]
Hello Friend,
Imatures are the best libraries .... lol

I was able to run the code without major problems. Executed by RGu

I would like to ask for more help.
My goal is to create a mechanism to perform to predict on demand.
The goal is to run this via the command line or through a webservice.

But I face a problem: Running this script via RScript creates a very large output and takes a lot of time, due to loading the template.

Do you have any hints or suggestions for a solution that can solve this problem.
Maybe an always running program with filessystem or piped stream

I'm not good at R and any suggestion would be of great value

**Comment by jtrecenti** [comment]
you should look at decryptr/decryptrAPI package

it uses OpenCPU and it is easy to set up. But it is not well documented yet

https://github.com/decryptr/decryptrAPI

**Comment by fabioravila** [comment]
wow...this is too complex to me....
I´ll give a try. tnkz
