### ISSUE TITLE
Conversão para Java

### ISSUE THREAD

**Issue by julianomqs** [decryptr/decryptr#20]
Olá, tudo bem?

Tenho interesse em utilizar sua biblioteca em meus projetos, mas como não conheço nem trabalho com a linguagem R estou considerando converter sua biblioteca para a linguagem Java.

Por isso, pergunto:

- Você acha que é viável a realização dessa conversão? A não utilização da linguagem R inviabilizaria o funcionamento da biblioteca por possuir recursos próprios que facilitam o desenvolvimento do algoritmo de quebra de captcha?

- Você autorizaria a realização dessa conversão?

- Se sim, você acha que somente o conhecimento da linguagem R é suficiente para a realização da conversão, ou seria necessário mais conhecimentos (processamento de imagens, etc.)?

Obrigado.

**Comment by jtrecenti** [comment]
Juliano,

O ideal para usar outras linguagens é montar um Docker com a API do modelo
e consumir via requisições locais. Aí fica tudo independente de linguagem.
Veja decryptr.netlify.com

**Comment by marcoscarvalho** [comment]
Acho que essa Issue pode ser até fechada após resposta do @jtrecenti

**Comment by dfalbel** [comment]
Legal! Vou deixar aqui como referência um container + instruções para criar um serviço rest com o decryptr.

https://github.com/decryptr/api
