### ISSUE TITLE
Existe a possibilidade de utilizar os modelos diretamente em base64?

### ISSUE THREAD

**Issue by Leoginski** [decryptr/decryptr#22]
Gostaria de saber se é possível decryptar um base64 ou até mesmo se eu poderia converter a imagem para algum formato específico em tempo de execução.

**Comment by dfalbel** [comment]
@Leoginski você pode dar uma olhada aqui: https://github.com/decryptr/api/blob/master/api.R#L19

**Comment by clente** [comment]
Fechando por inatividade. Reabrir caso necessário.
