### ISSUE TITLE
Problema com modelo TJRS.

### ISSUE THREAD

**Issue by glaucoqs** [decryptr/decryptr#23]
O download "tjrs" funciona, porém o decrypt não. Não existe o modelo para TJRS, e ao tentar um dos modelos preditivos, não consegue quebrar o captcha corretamente.

![image](https://user-images.githubusercontent.com/36828397/51912041-70827d80-23ba-11e9-9a17-028e4c0f8379.png)

**Comment by jtrecenti** [comment]
Olá, Glauco. De fato, não tem um modelo do decryptr ajustado para o TJRS.
Ele será adicionado no futuro.

**Comment by clente** [comment]
Modelo do TJRS adicionado.
