### ISSUE TITLE
Dificuldades para treinar um modelo novo

### ISSUE THREAD

**Issue by diogofr4** [decryptr/decryptr#24]
Estou tentando treinar um modelo para o TJRJ. Apliquei alguns filtros para limpar a imagem da captcha e facilitar a assertividade, ficando com uma imagem assim:

![image](https://user-images.githubusercontent.com/16695145/62783466-e0bd3a80-ba92-11e9-84cd-8f139d1c8ffe.png)

Renomeei 1000 captchas nesse estilo pra treinar um modelo, porém quando vou testar, não chega nem próximo da resposta correta. Estou fazendo alguma coisa errada no treinamento do modelo? Segue abaixo o script que usei:

captchasToTrain <- read_captcha(captchasInFolder, ans_in_path = TRUE)
model <- train_model(captchasToTrain, verbose = TRUE)

Não tenho muito conhecimento de ml, então tentei alterar o n_epochs aleatoriamente. Tentei com o padrão de 30, 10 e com 100. Ambos não acertaram nenhum caractere.
 @Edit
Segue o plot dos gráficos de 10 e de 100

![image](https://user-images.githubusercontent.com/16695145/62787482-30076900-ba9b-11e9-8b05-ea97e1444ecb.png)

![image](https://user-images.githubusercontent.com/16695145/62787516-40b7df00-ba9b-11e9-84e5-ce107ac65e1c.png)

**Comment by jtrecenti** [comment]
seu modelo parece estar acertando razoavelmente, está apenas overfittado. Verifique se você está fazendo o mesmo tratamento na base que você usa para ajustar o modelo e a base que você usa para testar o modelo.

**Comment by diogofr4** [comment]
Sim, estou usando o mesmo tratamento na base de teste. Já criei modelos com n_epochs = 5,7,10,100 e 500. Nenhum deles acertou a captcha quando eu usava a função decryptr. Não sei oq estou fazendo de errado.

**Comment by isa1821** [comment]
Eu aumentei a minha base de treino (por volta de 2500 captchas resolvidos) e o resultado melhorou significativamente.

**Comment by jtrecenti** [comment]
excelente! eu acredito que com uma base suficientemente grande, também não é preciso fazer pré-processamento.

**Comment by clente** [comment]
Fechando por inatividade. Reabrir caso necessário.
