### ISSUE TITLE
Problema utilizando scripts do repositório do decrypt

### ISSUE THREAD

**Issue by isa1821** [decryptr/decryptr#25]
Olá! Tudo bem? 

Eu estou treinando o modelo para um tipo específico de CAPTCHA e o meu modelo funcionou bem (+- 93%) quanto utilizei as funções read_captcha e train_model da própria biblioteca do decryptr.

Eu gostaria de melhorar o meu modelo e, para isso, gostaria de verificar o que acontece quando modifico alguns parâmetros das funções  layer.dropout e layer_cond_2d. Como não dá pra mudar estes parâmetros na biblioteca, eu estou tentando usar os scripts originais.

Porém, quando utilizo os arquivos model.R e read.R do repositório  https://github.com/decryptr/decryptr/releases, eu não consigo obter um resultado razoável. O novo modelo não chega nem a 10% de eficácia.

Dessa maneira, gostaria de confirmar se o repositório https://github.com/decryptr/decryptr/releases está atualizado.

**Comment by jtrecenti** [comment]
acho que o ideal seria você copiar o conteúdo da função train_model para um novo script e fazer as mudanças. 

A verdade é que essa função train_model deveria acabar, está muito improdutiva

**Comment by clente** [comment]
Fechando por inatividade. Reabrir caso necessário.
