### ISSUE TITLE
Modelo em memória após treinamento não resulta na mesma saída do modelo como arquivo salvo

### ISSUE THREAD

**Issue by tafm** [decryptr/decryptr#26]
Treinei um modelo pra detecção de caracteres como visto na imagem, após o treinamento com uso do model em memória o resultado está correto, se faço a leitura do arquivo gerado a partir do mesmo treinamento o resultado é diferente

![image](https://user-images.githubusercontent.com/12813195/65195435-a9f51f80-da55-11e9-9227-fc9c4d092013.png)

**Comment by jtrecenti** [comment]
eu acho que você precisa passar o dicionário no `load_model`, por exemplo:

```r
decryptr::load_model("./model.hdf5", labs = letters)
```

**Comment by tafm** [comment]
@jtrecenti é possível conseguir essa lista a partir de alguma função? ou setar na hora do treinamento, pois pelo que testei agora a ordem desse parâmetro importa

**Comment by jtrecenti** [comment]
Sim, a princípio é um parâmetro da read_captcha

**Comment by tafm** [comment]
Valeu!
