### ISSUE TITLE
Erros na instalação - CentOs 7

### ISSUE THREAD

**Issue by muriloneo** [decryptr/decryptr#33]
Estou com erros ao instalar este pacote em um servidor CentOs 7.

Tudo mais está instalado, porém quando faço a instalação do decryptr ele me retorna simplesmente:

`Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'decryptr' from GitHub:
  Failed to install 'decryptrModels' from GitHub:
  (converted from warning) installation of package 'tidyselect' had non-zero exit status`

Já fiz a reinstalação do openssl e vários pacotes.

Este repositório ainda é mantido?

**Comment by clente** [comment]
Murilo, de acordo com o erro que você colocou, o problema da instalação foi no pacote [`{tidyselect}`](https://github.com/r-lib/tidyselect). Minha sugestão é tentar entender o que está acontecendo por lá.

**Comment by muriloneo** [comment]
Realmente é lá. está dando muito problema.

estou rodando R como sudo agora para instalar todos os packages novamente. volto com informações. Obrigado.

**Comment by muriloneo** [comment]
`devtools::install_github("decryptr/decryptr")
Downloading GitHub repo decryptr/decryptr@HEAD
Downloading GitHub repo decryptr/decryptrModels@HEAD
   During startup - Warning message:
   Setting LC_CTYPE failed, using "C" 
v  checking for file '/tmp/RtmpCqmYrv/remotes1aa972e4ddbb/decryptr-decryptrModels-a54bca8/DESCRIPTION' ...
-  preparing 'decryptrModels':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'decryptrModels_0.0.1.9000.tar.gz'
   
Installing package into '/usr/lib64/R/library'
(as 'lib' is unspecified)
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'decryptr' from GitHub:
  Failed to install 'decryptrModels' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpCqmYrv/file1aa94de7347e/decryptrModels_0.0.1.9000.tar.gz' had non-zero exit status`

**Comment by clente** [comment]
Tentou ver isso? https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c

**Comment by muriloneo** [comment]
No mac funcionou muito bem e de primeira. meu problema é no CentOS 7.
mas vou verificar, se isso pode me ajudar de alguma forma.

**Comment by muriloneo** [comment]
Boa.
Mudou o erro, é um excelente sinal.

LC_ALL=C.UTF-8 sudo -i R
devtools::install_github("decryptr/decryptr")

Agora está pedindo o magick. ótimo!

**Comment by muriloneo** [comment]
Agora nos logs de tentativa de execução:

0|captcha  | <simpleError in if (tensorflow::tf_version() < "2.0.0") stop("TensorFlow version >= 2.0.0 is requires to load models in the SavedModel format.",     call. = FALSE): argument is of length zero>

**Comment by muriloneo** [comment]
Sucesso.
minha sugestão é ter muito disco e mais memória (sempre mais) haha! Obrigado pela atenção.
