### ISSUE TITLE
Como agir quando o captcha do mesmo site não possui o mesmo tamanho?

### ISSUE THREAD

**Issue by marcelfenerich** [decryptr/decryptr#36]
Estou tentando treinar um modelo e recebendo a seguinte mensagem:

`Answers to all captchas must have the same length`

Estou pegando o captcha do seguinte site:

http://consultacadastral.inss.gov.br/Esocial/api/imagem?d=I_009d15c0-a586-423b-b10e-36521bc5ae9a_1FF85DE2D634E9EC1DEFBB94B88BDBD5.lbroute_v131p040_internet&amp;uId=1604083697154

Grato

**Comment by SilasPDJ** [comment]
> Estou tentando treinar um modelo e recebendo a seguinte mensagem:
> 
> `Answers to all captchas must have the same length`
> 
> Estou pegando o captcha do seguinte site:
> 
> http://consultacadastral.inss.gov.br/Esocial/api/imagem?d=I_009d15c0-a586-423b-b10e-36521bc5ae9a_1FF85DE2D634E9EC1DEFBB94B88BDBD5.lbroute_v131p040_internet&amp;uId=1604083697154
> 
> Grato
Alguma atualização?
