### ISSUE TITLE
Someone has any idea how to manage it when it came to has different number of characters in captcha from the same website?

### ISSUE THREAD

**Issue by marcelfenerich** [decryptr/decryptr#38]
When I try to train a model using captchas from this site bellow I'm bumping up with this message:

http://consultacadastral.inss.gov.br/Esocial/api/imagem?d=I_009d15c0-a586-423b-b10e-36521bc5ae9a_1FF85DE2D634E9EC1DEFBB94B88BDBD5.lbroute_v131p040_internet&amp;uId=1604083697154

`Error in join_answers(ys) : 
  Answers to all captchas must have the same length`

There's a way to fix it?

**Comment by clente** [comment]
At this point we have no way of handling captchas of different length :(
