### ISSUE TITLE
package ‘h5py’ is not available (for R version 3.4.3) 

### ISSUE THREAD

**Issue by rafaelsmbr** [decryptr/decryptr#5]
> install.packages("h5py")
Warning message:
package ‘h5py’ is not available (for R version 3.4.3) 
> keras_rfb <- decryptrModels::read_model('rfb')
Error in keras::load_model_hdf5(file_path) : 
  The h5py Python package is required to save and load models

**Comment by ctlente** [comment]
See what I suggested [here](https://github.com/decryptr/decryptr/issues/4). This version of `read_model()` doesn't use `h5py`.

**Comment by rafaelsmbr** [comment]
`load_model` requires h5py.'


> read_model2 <- function(model_name) {
+   models <- decryptrModels:::models
+   path <- system.file("keras", package = "decryptrModels")
+   files <- dir(path, full.names = TRUE)
+   file_path <- normalizePath(files[grepl(model_name, files)])
+   labs <- models[grepl(model_name, models[["name"]]), ][["labs"]][[1]]
+   model <- keras:::keras$models$load_model(file_path)
+   m <- list(labs = labs, model = model)
+   class(m) <- "captcha"
+   return(m)
+ }
> keras_rfb <- read_model2('rfb')
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ImportError: `load_model` requires h5py.

Detailed traceback: 
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py", line 198, in load_model
    raise ImportError('`load_model` requires h5py.')

**Comment by ctlente** [comment]
Could you please run `read_model2()` line-by-line and give me the output for each line?

**Comment by ctlente** [comment]
I re-read your original question and just realized what you were trying to do. `h5py` isn't an R package, it's a _python_ package (googling that would have taken you to this [repo](https://github.com/h5py/h5py)).

You should install it with `pip`.
