### ISSUE TITLE
Problems with using predict after training model

### ISSUE THREAD

**Issue by claudiolucinda** [decryptr/decryptr#6]
Hi all,
I think I need your help with one thing. After training the model, I want it to predict a new captcha, and I am having some problems with your code (I looked at your vignettes to reach this point). This is what I tried with the error messages:

> a<-prepare(read_captcha("./Captchas_test/captcha.png"))
> predict(modelo,arq=a)
Error in keras_array(x) : argument "x" is missing, with no default

Do you have some ideas on why this might be happening?

**Comment by ctlente** [comment]
Hey Claudio,

At the moment this package is going through some intense refactoring. I suggest you try using [this fork](https://github.com/ctlente/decryptr) to see if your problem persists.

That version of `decryptr` works a quite a bit differently than the one you're using, but hopefully it'll be simple to get the hang of it. Everything is explained in the readme and in the documentation, but if you need any help please post it as an issue on that repo.

Hope this helps!

**Comment by claudiolucinda** [comment]
Thanks! I have already switched.
